import sys

from PyQt5 import (
    QtCore, 
    QtWidgets, 
    QtGui
)
from PyQt5.QtCore import (
    Qt, 
    QCoreApplication, 
    QThread, 
    pyqtSignal
)
from PyQt5.QtWidgets import (
    QApplication, 
    QComboBox, 
    QDialog,
    QDialogButtonBox, 
    QFormLayout, 
    QGridLayout, 
    QGroupBox, 
    QHBoxLayout,
    QLabel, 
    QLineEdit, 
    QMenu, 
    QMenuBar, 
    QPushButton, 
    QSpinBox, 
    QTextEdit,
    QVBoxLayout,
    QWidget,
    QStackedWidget,
    QListWidget,
    QRadioButton,
    QCheckBox,
    QToolButton,
    QMainWindow,
    QAction,
    QSizePolicy,
)

from PyQt5.QtGui import (
    QIcon, 
    QCursor, 
    QWindow, 
    QGuiApplication
)

from cherryui import Ui_MainWindow
from sidebar import Sidebar

#from home import Home
#from progress import Progress
#from history import History


class Cherry(QMainWindow, Ui_MainWindow):
    """ Main window that holds the main layout """

    def __init__(self, parent=None):
        super(Cherry, self).__init__()

        self.setupUi(self)

        ## Override sidebar generated by Qt designer
        self.sidebar = Sidebar(self.centralWidget)

        # Rearrange widget order
        self.horizontalLayout.removeWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.sidebar)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.setWindowTitle("Cherry")

    def closeEvent(self, closeEvent):
        QCoreApplication.exit()
